#SPDX-License-Identifier: MIT-0
---
# tasks file for Roles



- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
  tags: update

- name: Install additional required packages
  apt:
    name:
      - python3
      - python3-apt
    state: present
    update_cache: yes


