---

- name: pull the Docker image
  ansible.builtin.docker_image:
    name: "{{ image_name }}"
    source: pull
    tag: "{{ image_tag }}"
  

- name: Stop and remove existing container if running
  ansible.builtin.docker_container:
    name: "{{ app_container_name }}"
    state: absent
    force_kill: yes
  ignore_errors: yes

- name: Run the Docker container
  ansible.builtin.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: started
    restart_policy: always
    ports:
      - "{{ app_port }}:8080"