#install Docker and set as default
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install prerequisite packages for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - lsb-release
      - software-properties-common
    state: present
  become: yes

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Set Ubuntu codename
  command: lsb_release -cs
  register: ubuntu_codename
  changed_when: false

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
    state: present
  become: yes


- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: yes

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "User"
    groups: docker
    append: yes
  become: yes

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version

- name: Display Docker version
  ansible.builtin.debug:
    msg: "Docker version: {{ docker_version.stdout }}"