---

# - name: Install Nginx
#   apt:
#     name: nginx
#     state: present
#   become: yes

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
  become: yes

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  become: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes
