---
- name: Upgrade Python to compatible version
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Add deadsnakes PPA for newer Python
      raw: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:deadsnakes/ppa
        apt-get update
      changed_when: true

    - name: Install Python 3.10 and dependencies
      raw: |
        apt-get install -y python3.10 python3.10-distutils python3.10-venv python3.10-dev
      changed_when: true

    - name: Force update Python3 symlink
      raw: |
        rm -f /usr/bin/python3
        ln -sf /usr/bin/python3.10 /usr/bin/python3
        ls -la /usr/bin/python3
        /usr/bin/python3 --version
      register: link_result
      changed_when: true

    - name: Show symlink result
      debug:
        var: link_result.stdout_lines

    - name: Install pip for Python 3.10
      raw: |
        curl -sS https://bootstrap.pypa.io/get-pip.py | /usr/bin/python3.10
        /usr/bin/python3 -m pip install --upgrade pip setuptools
      changed_when: true

    - name: Final verification
      raw: /usr/bin/python3 --version && /usr/bin/python3 -c "import sys; print(sys.version)"
      register: final_check
      changed_when: false

    - name: Show final Python info
      debug:
        var: final_check.stdout_lines

- name: Setup Application
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - Roles