---
- name: Upgrade Python to compatible version
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Add deadsnakes PPA for newer Python
      raw: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:deadsnakes/ppa
        apt-get update
      changed_when: true

    - name: Install Python 3.10
      raw: |
        apt-get install -y python3.10 python3.10-distutils python3.10-venv
        update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
        update-alternatives --set python3 /usr/bin/python3.10
        python3 --version
      register: python_install
      changed_when: true

    - name: Install pip for Python 3.10
      raw: |
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
        python3 -m pip install --upgrade pip
      changed_when: true

    - name: Verify Python version
      raw: python3 --version
      register: final_version
      changed_when: false

    - name: Show final Python version
      debug:
        var: final_version.stdout

- name: Setup Application
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - Roles