---
- name: Fix Python installation
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Check available Python versions
      raw: ls -la /usr/bin/python3*
      register: python_versions
      changed_when: false
      ignore_errors: yes

    - name: Display available Python versions
      debug:
        var: python_versions.stdout_lines

    - name: Fix Python3 symlink
      raw: |
        rm -f /usr/bin/python3
        ln -s /usr/bin/python3.6 /usr/bin/python3
        ls -la /usr/bin/python3
        /usr/bin/python3 --version
      register: fix_result
      changed_when: true

    - name: Verify Python is working
      raw: /usr/bin/python3 --version
      register: verify
      changed_when: false

    - name: Show Python version
      debug:
        var: verify.stdout

- name: Setup Application
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - Roles