
---

# tasks file for Roles

- name: Bootstrap Python on remote server
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Install Python 3
      raw: apt-get update && apt-get install -y python3 python3-apt
      changed_when: false



- name: Setup Application
  hosts: all
  become: yes
  roles:
    - Roles
