---
- name: Bootstrap Python on remote server
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Check if Python3 exists
      raw: which python3
      register: python_exists
      ignore_errors: yes
      changed_when: false

    - name: Install Python 3 if not found
      raw: |
        apt-get update
        apt-get install -y python3 python3-apt python3-pip
      when: python_exists.rc != 0

    - name: Ensure Python3 is available
      raw: python3 --version
      changed_when: false

- name: Setup Application
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - Roles