---
- name: Setup Python environment on VM
  hosts: server
  become: yes
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Ensure Python 3.10 packages installed
      ansible.builtin.apt:
        name:
          - python3.10
          - python3.10-venv
          - python3.10-distutils
          - python3.10-dev
        state: present
        install_recommends: yes

    - name: Verify Python version
      ansible.builtin.command: python3 --version
      register: python_version

    - name: Show installed Python version
      ansible.builtin.debug:
        msg: "Installed Python version is {{ python_version.stdout }}"
