---
- name: Bootstrap Python on remote server
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Update apt cache
      raw: apt-get update -y
      changed_when: false

    - name: Install Python packages
      raw: apt-get install -y python3 python3-apt python3-minimal
      changed_when: false

- name: Verify Python and gather facts
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Setup Application
  hosts: all
  become: yes
  roles:
    - Roles