---
- name: Upgrade Python to compatible version
  hosts: server
  become: yes
  tasks:

    - name: Ensure dependencies for adding PPA
      ansible.builtin.apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Add deadsnakes PPA for newer Python
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Python 3.10 minimal if not already installed
      ansible.builtin.apt:
        name: python3.10-minimal
        state: present

    - name: Install optional Python 3.10 packages if available
      ansible.builtin.apt:
        name:
          - python3.10
          - python3.10-distutils
          - python3.10-venv
          - python3.10-dev
        state: present
        install_recommends: yes
      ignore_errors: yes   # يسمح باستمرار التشغيل حتى لو بعض الحزم غير موجودة

    - name: Ensure python3 points to python3.10
      ansible.builtin.command: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2
      args:
        creates: /usr/bin/python3

    - name: Verify Python version
      ansible.builtin.command: python3 --version
      register: python_version

    - name: Show installed Python version
      ansible.builtin.debug:
        msg: "Installed Python version is {{ python_version.stdout }}"
