name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'CenterApi/**'
      - '.github/workflows/CI.yml'
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore
        run: dotnet restore CenterApi/CenterApi.sln

      # Build
      - name: Build
        run: dotnet build CenterApi/CenterApi.sln --configuration Release --no-restore

      
      # Build Docker image
      - name: Build Docker image
        run: docker build -t centerapi-image -f CenterApi/dockerfile CenterApi

      # Push Docker image to Docker Hub (optional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag centerapi-image ${{ secrets.DOCKERHUB_USERNAME }}/centerapi-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/centerapi-image:latest
